version: "3.7"

services:
  database_unic:
    image: postgres
    container_name: database_unic
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=unic
      - POSTGRES_DB=unic
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: unic
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database_unic
    depends_on:
      - database_unic

volumes:
  pgdata:
    driver: local